spring:
  graphql:
    graphiql:
      enabled: true # graphiql? ?? ??? ?? ?? (localhost:8080/graphiql)
      printer:
        enabled: true # show-sql? ?? graphql ??? ?? ??
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    drvier-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: sa
    password:
  sql: # ???? ???? ??? ???? ???? ??
    init:
      mode: always
      schema-location:  # ?????? ??? SQL ??
      data-location:  # ?????? ?? ??? INSERT SQL ??
  h2:
    console:
      path: /h2
      enabled: true
